version: '2'
services:
  app:
    build:
        context: .
        dockerfile: docker/Dockerfile
    volumes:
        - ./:/var/www/
    ports:
        - "80:80"
        - "8888:8888"
    links:
        - appdb
    environment:
        - LUCEE_PASSWORD=myLuceeRootPassword!
        - LUCEE_JAVA_OPTS=-Xms1024m -Xmx1024m
  appdb:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD : mySQLRootPassword!
        MYSQL_DATABASE : PortMan
    ports:
      - "3306:3306"